version: '3.8'

services:
  redis-server:
    hostname: redis-server
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data  # ✅ Persistent volume for Redis data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    expose:
      - "5001"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis-server
      - STAGE=dev
    volumes:
      - ./backend:/app  # ✅ Bind mount for local development
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000 --reload-include "*.py"
    depends_on:
      - db
      - redis-server

  db:
    image: postgres:alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=containerCrm
    volumes:
      - postgres_data:/var/lib/postgresql/data  # ✅ Persistent volume for PostgreSQL

volumes:
  redis_data: 
  postgres_data:  
