# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --settings=backend/pyproject.toml

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        exclude: 'docs/'
        description: "Black: The uncompromising Python code formatter"
        require_serial: true
        types: [ python ]

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: 'docs/'
        args:
          - --ignore=E501,W503
          - --per-file-ignores=*/__init__.py:F401 */settings/*.py:F405 */migrate_usac_worker/*.py:F402 */demo_data/*.py:F401

  # https://pre-commit.com/#repository-local-hooks
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry check (local)
        description: Ensure pyproject.toml file is valid
        entry: poetry check -n
        language: system
        pass_filenames: false
        files: ^pyproject\.toml$

      - id: poetry-lock
        name: poetry lock (local)
        description: Ensure lock file is up-to-date
        entry: bash -c 'poetry lock -n --check || poetry lock -n --no-update'
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock)$

      - id: poetry-export
        name: poetry export (local)
        description: Export requirements during transition period
        entry: bash -c 'poetry export -f requirements.txt --without-hashes --output requirements.txt; git add -u' --
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock|(constraints|requirements)\.txt)$

      - id: poetry-export-dev
        name: poetry export dev (local)
        description: Export dev requirements during transition period
        entry: bash -c 'poetry export -f requirements.txt --without-hashes --dev --output requirements-dev.txt; git add -u' --
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock|(constraints|requirements(-dev)?)\.txt)$

      # - id: make-migrations
      #   name: make migrations
      #   description: make aerich migrations
      #   entry: bash -c 'cd backend && python3 -m src.migrate'
      #   pass_filenames: false
      #   language: system
