# Pip imports
from tortoise import Tortoise


models = [
    "aerich.models",
    "src.database.models.subtotal_balance",
    "src.database.models.tax_balance",
    "src.database.models.rent_period_tax_balance",
    "src.database.models.inventory_address",
    "src.database.models.customer.order_customer",
    "src.database.models.customer.customer_contact",
    "src.database.models.customer.old_customer",
    "src.database.models.inventory.depot",
    "src.database.models.inventory.container_inventory",
    "src.database.models.inventory.inventory_category",
    "src.database.models.inventory.other_inventory",
    "src.database.models.inventory.vendor",
    "src.database.models.orders.coupon_code",
    "src.database.models.orders.order",
    "src.database.models.orders.coupon_code_order",
    "src.database.models.orders.coupon_line_item_value",
    "src.database.models.orders.line_item",
    "src.database.models.orders.accessory_line_item",
    "src.database.models.pricing.container_product",
    "src.database.models.pricing.location_price",
    "src.database.models.pricing.product_category",
    "src.database.models.pricing.other_product",
    "src.database.models.account",
    "src.database.models.address",
    "src.database.models.assistant",
    "src.database.models.audit",
    "src.database.models.logistics_zones",
    "src.database.models.auth_management_token",
    "src.database.models.cms",
    "src.database.models.comission",
    "src.database.models.cost_type",
    "src.database.models.customer_application_response",
    "src.database.models.customer_application_schema",
    "src.database.models.delivery",
    "src.database.models.driver",
    "src.database.models.event_history",
    "src.database.models.fee_type",
    "src.database.models.fee",
    "src.database.models.file_upload",
    "src.database.models.location_distance",
    "src.database.models.misc_cost",
    "src.database.models.note",
    "src.database.models.order_address",
    "src.database.models.total_order_balance",
    "src.database.models.order_comission",
    "src.database.models.order_contract",
    "src.database.models.order_credit_card",
    "src.database.models.order_id_counter",
    "src.database.models.order_tax",
    "src.database.models.quote_searches",
    "src.database.models.rent_period_balance",
    "src.database.models.rent_period_fee_balance",
    "src.database.models.rent_period_fee",
    "src.database.models.rent_period_tax",
    "src.database.models.rent_period_total_balance",
    "src.database.models.rent_period",
    "src.database.models.rental_history",
    "src.database.models.tax",
    "src.database.models.team_member",
    "src.database.models.transaction_type",
    "src.database.models.user",
    "src.database.models.reports",
    "src.database.models.container_product_attribute",
    "src.database.models.container_attribute",
    "src.database.models.vendor_types",
    "src.database.models.country",
    "src.database.models.role",
    "src.database.models.order_fee_balance",
    "src.database.models.notification",
    "src.database.models.notification_history",
    "src.database.models.payment_method",
    "src.database.models.fixed_location_price",
]


def init_models():
    Tortoise.init_models(
        models,
        "models",
    )
